// let x=10;
// let y='5';
// console.log(x+y);
// let x=10;
// console.log(x*2);
// let x=10;
// console.log(-null);
// let x=10;
// console.log(x*2);
// let x=10;
// console.log(10/'2');
// let x=10;
// console.log(10%3);
// let x=10;
// console.log(x**2);
// let x=10;
// let y=5;
// console.log(x>y&&y<x);
// let x=10;
// let y='10';
// console.log(x===y);
// let x=null;
// let y='dafault';
// console.log(x??y);
// let x=10;
// let y='default';
// console.log(x||y);
// let x=true;
// console.log(!x);
// let x=10;
// let y=5;
// console.log(x&y);
// let x=10;
// let y=5;
// console.log(x|y);
// let x=10;
// let y=5;
// console.log(x^y);
// let x=10;
// let y=++x;
// console.log(x,y);
// let x=10;
// let y=x++;
// console.log(x&y);
// let x=10;
// console.log(++x);
// let x=10;
// console.log(x++);
// let x=10;
// let y=--x;
// console.log(x&y);
// let x=10;
// let y=x--;
// console.log(x&y);
// let x=10;
// let y=x>5?'yes':'no';
// console.log(y);
// let x=10;
// let y=x>5?'yes':x>3?'maybe':'no';
// console.log(y);
// const obj={a:{b:'c'}};
// console.log(obj?.a?.b);
// const obj={a:{b:'c'}};
// console.log(obj?.a?.c);
// const obj={a:{b:'c'}};
// console.log(obj?.b?.c);
// let x=null;
// let y=x??'default';
// console.log(y);
// let x=undefined;
// let y=x??'default';
// console.log(y);
let x=0;
let y=x??'default';
console.log(y);

